### ISSUE TITLE
Move common sections to config file

### ISSUE THREAD

**Issue by hmubarak** [qcri/LLMeBench#18]
common configuration for GPT models can be moved outside individual codes, ex: in AraGend_ChatGPT_ZeroShot.py, all model_args can be put in a file (ex: config_ChatGPT.json) such that all codes can read from it without duplications.

also, as class_labels cannot be listed in many tasks (ex: MT, the combination of emotions, etc.), we want to tell users that this field is optional.

def config():
    return {
        "dataset": ArabGendDataset,
        "dataset_args": {},
        "task": DemographyGenderTask,
        "task_args": {},
        "model": GPTModel,
        "model_args": {
            "api_type": "azure",
            "api_version": "2023-03-15-preview",
            "api_base": os.environ["AZURE_API_URL"],
            "api_key": os.environ["AZURE_API_KEY"],
            "engine_name": "gpt",
            "class_labels": ["m", "f"],
            "max_tries": 3,
        },
        "general_args": {"data_path": "data/demography/gender/gender-test.txt"},
    }

**Comment by fdalvi** [comment]
#204
