### ISSUE TITLE
Environment variable for engine_name

### ISSUE THREAD

**Issue by hmubarak** [qcri/LLMeBench#20]
Please add an option to read engine_name from an environment variable,
ex: Location_ChatGPT_ZeroShot.py

            "api_base": os.environ["AZURE_API_URL"],
            "api_key": os.environ["AZURE_API_KEY"],
            "engine_name": os.environ["ENGINE_NAME"],  <<<< HARE >>>

**Comment by fdalvi** [comment]
All assets now use this convention!
